"""Small hand-curated lists that make the data usable by a real patient.

CONDITION_GROUPS  everyday words ("sugar", "BP", "kidney") -> all DrugCentral conditions that mean the same thing,
                  so a contraindication recorded on "Chronic heart failure" is not missed when the user types "heart failure".
CASCADE_RULES     textbook prescribing cascades. A cascade is only reported when the graph itself also has the
                  CAUSES edge (Hetionet) and the TREATS edge (DrugCentral); the rule just says which ones make clinical sense.
"""

# group label: (what users type, DrugCentral condition names in the group)
CONDITION_GROUPS = {
    "Diabetes": (["diabetes", "diabetes mellitus", "sugar", "blood sugar", "high sugar", "type 2 diabetes", "t2dm", "dm",
                  "diabetic"],
                 ["Diabetes mellitus", "Diabetes mellitus type 2", "Diabetic - poor control", "Severe Diabetes Mellitus",
                  "Treatment Refractory Type 2 Diabetes Mellitus", "Type 2 diabetes mellitus in obese",
                  "Disorder due to type 2 diabetes mellitus"]),
    "High blood pressure": (["hypertension", "high blood pressure", "high bp", "bp", "blood pressure", "htn"],
                            ["Hypertensive disorder", "Essential hypertension", "Malignant essential hypertension",
                             "Malignant hypertension", "Hypertensive urgency", "Hypertensive Emergencies",
                             "Hypertensive emergency", "Hypertension with Left Ventricular Hypertrophy",
                             "Paroxysmal hypertension"]),
    "Low blood pressure": (["low bp", "low blood pressure", "hypotension"],
                           ["Low blood pressure", "Orthostatic hypotension"]),
    "Kidney disease": (["kidney", "kidney disease", "kidney problem", "ckd", "chronic kidney disease", "renal failure",
                        "renal disease", "renal impairment", "dialysis"],
                       ["Kidney disease", "Chronic kidney disease", "Impaired renal function disorder", "Renal impairment",
                        "End stage renal disease", "End stage renal failure", "Renal failure syndrome",
                        "Severe renal impairment undergoing dialysis", "Renal dialysis", "Uremia"]),
    "Liver disease": (["liver", "liver disease", "liver problem", "cirrhosis", "liver cirrhosis", "hepatic impairment"],
                      ["Disease of liver", "Hepatic failure", "Cirrhosis of liver", "Compensated cirrhosis",
                       "Decompensated cirrhosis of liver", "Moderate hepatic impairment", "Severe hepatic impairment",
                       "Chronic Hepatic Disease", "End stage liver disease", "Decreased liver function",
                       "Acute hepatic failure"]),
    "Asthma": (["asthma", "wheezing"],
               ["Asthma", "Acute exacerbation of asthma", "Exacerbation of asthma", "Bronchospasm", "Eosinophilic asthma",
                "Allergic asthma", "Non-allergic asthma", "Severe asthma", "Refractory Extrinsic Asthma"]),
    "COPD": (["copd", "emphysema", "chronic bronchitis"],
             ["Pulmonary emphysema", "Severe chronic obstructive pulmonary disease", "Chronic bronchitis",
              "Chronic Obstructive Pulmonary Disease with Bronchospasms",
              "Acutely Deteriorating Chronic Obstructive Pulmonary Disease"]),
    "Peptic ulcer": (["peptic ulcer", "ulcer", "stomach ulcer", "gastric ulcer", "duodenal ulcer"],
                     ["Peptic ulcer", "Gastric ulcer", "Duodenal ulcer disease", "Gastrointestinal ulcer",
                      "Acute peptic ulcer", "Chronic peptic ulcer", "Acute gastric ulcer with perforation",
                      "Acute gastric ulcer with hemorrhage", "Acute peptic ulcer with hemorrhage"]),
    "Acidity / reflux": (["acidity", "gerd", "reflux", "acid reflux", "heartburn"],
                         ["Gastroesophageal reflux disease", "Peptic reflux disease", "Heartburn"]),
    "Pregnancy": (["pregnancy", "pregnant"],
                  ["Pregnancy, function", "Third trimester pregnancy", "Second trimester pregnancy"]),
    "Breastfeeding": (["breastfeeding", "breast feeding", "lactation", "nursing mother"],
                      ["Breastfeeding (mother)", "Lactation"]),
    "Heart failure": (["heart failure", "chf", "congestive heart failure", "weak heart"],
                      ["Heart failure", "Chronic heart failure", "Congestive heart failure", "Acute heart failure",
                       "Decompensated cardiac failure", "Left heart failure", "Decompensated chronic heart failure",
                       "Worsening of Chronic Heart Failure", "High output heart failure",
                       "Acute exacerbation of chronic congestive heart failure"]),
    "Heart attack (past or recent)": (["heart attack", "myocardial infarction", "mi"],
                                      ["Myocardial infarction", "Myocardial infarction in recovery phase",
                                       "Non-Q wave myocardial infarction"]),
    "Angina / coronary artery disease": (["angina", "coronary artery disease", "cad", "chest pain heart"],
                                         ["Angina pectoris", "Disorder of coronary artery", "Coronary arteriosclerosis",
                                          "Acute coronary syndrome", "Prinzmetal angina", "Progressive Angina Pectoris"]),
    "Stroke": (["stroke", "cva", "brain stroke", "paralysis"],
               ["Cerebrovascular accident", "Cerebrovascular disease", "Acute cerebrovascular insufficiency",
                "Acute Thromboembolic Stroke", "Hemorrhagic cerebral infarction", "Cerebral infarction",
                "Cerebral hemorrhage"]),
    "Slow or irregular heartbeat": (["arrhythmia", "irregular heartbeat", "slow heart rate", "bradycardia", "heart block",
                                     "long qt", "qt prolongation"],
                                    ["Prolonged QT interval", "Congenital long QT syndrome", "Bradycardia",
                                     "Sinus bradycardia", "Heart block", "First Degree Atrioventricular Heart Block",
                                     "Tachyarrhythmia", "Life-Threatening Cardiac Arrhythmias"]),
    "Atrial fibrillation": (["atrial fibrillation", "af", "afib"], ["Atrial fibrillation"]),
    "Bleeding disorder": (["bleeding disorder", "bleeding", "haemophilia", "hemophilia", "clotting disorder"],
                          ["Blood coagulation disorder", "Hemophilia", "Hemorrhage"]),
    "Anaemia": (["anaemia", "anemia", "low hb", "low haemoglobin", "low hemoglobin"],
                ["Anemia", "Hemolytic anemia", "Aplastic anemia", "Megaloblastic anemia",
                 "Megaloblastic anemia due to folate deficiency"]),
    "G6PD deficiency": (["g6pd", "g6pd deficiency"],
                        ["Anemia due to enzyme deficiency", "Glucose-6-phosphate dehydrogenase deficiency anemia"]),
    "High cholesterol": (["high cholesterol", "cholesterol", "hyperlipidemia", "hyperlipidaemia", "dyslipidemia",
                          "lipids"],
                         ["Hypercholesterolemia", "Hyperlipidemia", "Mixed hyperlipidemia", "Dyslipidemia"]),
    "Depression": (["depression", "depressed"], ["Depressive disorder", "Severe depression", "Major depressive disorder"]),
    "Epilepsy / seizures": (["epilepsy", "seizures", "seizure", "fits", "convulsions"],
                            ["Epilepsy", "Uncontrolled Epilepsy", "Lowered convulsive threshold", "Partial seizure",
                             "Tonic-clonic seizure", "Tonic-clonic epilepsy", "Idiopathic generalized epilepsy",
                             "Mixed Epilepsy", "Absence seizure", "Myoclonic seizure"]),
    "Glaucoma": (["glaucoma"],
                 ["Glaucoma", "Angle-closure glaucoma", "Open-angle glaucoma", "Secondary angle-closure glaucoma",
                  "Secondary glaucoma", "Primary Closed Angle Glaucoma", "Pupillary Block Glaucoma",
                  "Aggravated Glaucoma", "Malignant glaucoma", "Neovascular glaucoma"]),
    "Gout": (["gout", "uric acid", "high uric acid"], ["Gout", "Hyperuricemia"]),
    "Underactive thyroid": (["hypothyroidism", "low thyroid", "underactive thyroid", "thyroid"],
                            ["Hypothyroidism", "Mild Hypothyroidism", "Myxedema", "Hashimoto thyroiditis"]),
    "Overactive thyroid": (["hyperthyroidism", "overactive thyroid", "thyrotoxicosis"],
                           ["Hyperthyroidism", "Thyrotoxicosis", "Thyrotoxic crisis"]),
    "Enlarged prostate": (["prostate", "enlarged prostate", "bph", "urinary retention"], ["Benign prostatic hyperplasia"]),
    "Myasthenia gravis": (["myasthenia", "myasthenia gravis"], ["Myasthenia gravis"]),
    "Parkinson's disease": (["parkinson", "parkinsons", "parkinson's", "parkinson's disease"],
                            ["Parkinsonism", "Parkinson's disease"]),
    "Dementia": (["dementia", "alzheimer", "alzheimers", "alzheimer's"],
                 ["Senile dementia", "Dementia", "Alzheimer's disease"]),
    "Tuberculosis": (["tb", "tuberculosis"],
                     ["Acute tuberculosis", "Inactive tuberculosis", "Tuberculosis", "Pulmonary tuberculosis",
                      "Active tuberculosis"]),
    "Piles": (["piles", "hemorrhoids", "haemorrhoids"], ["Hemorrhoids", "Bleeding hemorrhoids"]),
}

# Each rule: the side effect (Hetionet names, regex), which drugs cause it (ATC class prefixes or names),
# and which conditions a second drug would be treating (DrugCentral names, regex).
CASCADE_RULES = [
    {"effect": "ankle swelling (oedema)", "effect_re": "(?i)oedema( peripheral| aggravated)?",
     "cause_atc": ["C08"], "cause_names": [], "treat_re": "(?i)(edema|peripheral edema|peripheral edema due to .*|edema due to .*|renal disease with edema)"},
    {"effect": "raised blood pressure", "effect_re": "(?i)hypertension",
     "cause_atc": ["M01A", "H02A"], "cause_names": [],
     "treat_re": "(?i)(hypertensive disorder|essential hypertension|malignant (essential )?hypertension)"},
    {"effect": "stomach irritation or ulcer", "effect_re": "(?i)(dyspepsia|gastric ulcer|duodenal ulcer|chronic peptic ulcer|peptic ulcer|gastritis|gastrooesophageal reflux disease)",
     "cause_atc": ["M01A", "B01AC", "H02A"], "cause_names": [],
     "treat_re": "(?i)(peptic ulcer|gastric ulcer|duodenal ulcer.*|gastroesophageal reflux disease|heartburn|erosive esophagitis)"},
    {"effect": "raised uric acid or gout", "effect_re": "(?i)(hyperuricaemia|gout|gout acute|gout attack|gouty arthritis)",
     "cause_atc": ["C03A", "C03C"], "cause_names": ["pyrazinamide", "ethambutol"],
     "treat_re": "(?i)(gout|articular gout|hyperuricemia)"},
    {"effect": "low potassium", "effect_re": "(?i)hypokalaemia",
     "cause_atc": ["C03A", "C03C", "H02A"], "cause_names": [], "treat_re": "(?i)hypokalemia.*"},
    {"effect": "constipation", "effect_re": "(?i)constipation( aggravated)?",
     "cause_atc": ["N02A", "C08DA", "N06AA", "A12AA"], "cause_names": [], "treat_re": "(?i)constipation"},
    {"effect": "dry cough", "effect_re": "(?i)cough( increased)?",
     "cause_atc": ["C09A"], "cause_names": [], "treat_re": "(?i)cough"},
    {"effect": "drug-induced parkinsonism or stiffness",
     "effect_re": "(?i)(drug-induced parkinsonism|parkinsonism|extrapyramidal disorder|extrapyramidal symptoms)",
     "cause_atc": ["N05A", "A03FA", "N07CA"], "cause_names": [],
     "treat_re": "(?i)(parkinsonism|parkinson's disease|extrapyramidal disease)"},
    {"effect": "raised blood sugar", "effect_re": "(?i)(hyperglycaemia|diabetes mellitus|blood glucose increased)",
     "cause_atc": ["H02A", "C03A", "N05AH", "N05AX"], "cause_names": [],
     "treat_re": "(?i)(diabetes mellitus.*|type 2 diabetes.*)"},
    {"effect": "underactive thyroid", "effect_re": "(?i)hypothyroidism",
     "cause_atc": ["C01BD"], "cause_names": ["lithium carbonate", "lithium"], "treat_re": "(?i)hypothyroidism"},
    {"effect": "tremor", "effect_re": "(?i)(tremor|tremor fine)",
     "cause_atc": ["N03AG", "R03AC", "R03CC"], "cause_names": ["lithium carbonate", "lithium"], "treat_re": "(?i)essential tremor"},
    {"effect": "diarrhoea", "effect_re": "(?i)(diarrhoea|antibiotic-associated diarrhea)",
     "cause_atc": ["J01", "A10BA"], "cause_names": [], "treat_re": "(?i)(diarrh(o)?ea.*|traveler's diarrhea)"},
    {"effect": "thrush or fungal infection", "effect_re": "(?i).*candid.*",
     "cause_atc": ["J01", "H02A", "R03BA"], "cause_names": [], "treat_re": "(?i).*candid.*"},
    {"effect": "dizziness or vertigo", "effect_re": "(?i)(dizziness|vertigo|dizziness postural)",
     "cause_atc": ["C02", "C03", "C07", "C08", "C09", "N03"], "cause_names": [],
     "treat_re": "(?i)(vertigo.*|m.ni.re's disease|dizziness)"},
    {"effect": "difficulty passing urine", "effect_re": "(?i)urinary retention",
     "cause_atc": ["N04A", "A03B", "N06AA", "R06A"], "cause_names": [],
     "treat_re": "(?i)(benign prostatic hyperplasia|urinary retention)"},
    {"effect": "sleeplessness", "effect_re": "(?i)(insomnia|initial insomnia)",
     "cause_atc": ["N06AB", "N06B", "R03CC", "H02A"], "cause_names": [], "treat_re": "(?i)insomnia.*"},
]
