"""Small hand-curated lists that make the data usable by a real patient.

CONDITION_GROUPS  everyday words ("sugar", "BP", "kidney") -> all DrugCentral conditions that mean the same thing,
                  so a contraindication recorded on "Chronic heart failure" is not missed when the user types "heart failure".
CASCADE_RULES     textbook prescribing cascades. A cascade is only reported when the graph itself also has the
                  CAUSES edge (Hetionet) and the TREATS edge (DrugCentral); the rule just says which ones make clinical sense.
"""

# group label: (what users type, DrugCentral condition names in the group)
CONDITION_GROUPS = {
    "Diabetes": (["diabetes", "diabetes mellitus", "sugar", "blood sugar", "high sugar", "type 2 diabetes", "t2dm", "dm",
                  "diabetic"],
                 ["Diabetes mellitus", "Diabetes mellitus type 2", "Diabetic - poor control", "Severe Diabetes Mellitus",
                  "Treatment Refractory Type 2 Diabetes Mellitus", "Type 2 diabetes mellitus in obese",
                  "Disorder due to type 2 diabetes mellitus"]),
    "High blood pressure": (["hypertension", "high blood pressure", "high bp", "bp", "blood pressure", "htn"],
                            ["Hypertensive disorder", "Essential hypertension", "Malignant essential hypertension",
                             "Malignant hypertension", "Hypertensive urgency", "Hypertensive Emergencies",
                             "Hypertensive emergency", "Hypertension with Left Ventricular Hypertrophy",
                             "Paroxysmal hypertension"]),
    "Low blood pressure": (["low bp", "low blood pressure", "hypotension"],
                           ["Low blood pressure", "Orthostatic hypotension"]),
    "Kidney disease": (["kidney", "kidney disease", "kidney problem", "ckd", "chronic kidney disease", "renal failure",
                        "renal disease", "renal impairment", "dialysis"],
                       ["Kidney disease", "Chronic kidney disease", "Impaired renal function disorder", "Renal impairment",
                        "End stage renal disease", "End stage renal failure", "Renal failure syndrome",
                        "Severe renal impairment undergoing dialysis", "Renal dialysis", "Uremia"]),
    "Liver disease": (["liver", "liver disease", "liver problem", "cirrhosis", "liver cirrhosis", "hepatic impairment"],
                      ["Disease of liver", "Hepatic failure", "Cirrhosis of liver", "Compensated cirrhosis",
                       "Decompensated cirrhosis of liver", "Moderate hepatic impairment", "Severe hepatic impairment",
                       "Chronic Hepatic Disease", "End stage liver disease", "Decreased liver function",
                       "Acute hepatic failure"]),
    "Asthma": (["asthma", "wheezing"],
               ["Asthma", "Acute exacerbation of asthma", "Exacerbation of asthma", "Bronchospasm", "Eosinophilic asthma",
                "Allergic asthma", "Non-allergic asthma", "Severe asthma", "Refractory Extrinsic Asthma"]),
    "COPD": (["copd", "emphysema", "chronic bronchitis"],
             ["Pulmonary emphysema", "Severe chronic obstructive pulmonary disease", "Chronic bronchitis",
              "Chronic Obstructive Pulmonary Disease with Bronchospasms",
              "Acutely Deteriorating Chronic Obstructive Pulmonary Disease"]),
    "Peptic ulcer": (["peptic ulcer", "ulcer", "stomach ulcer", "gastric ulcer", "duodenal ulcer"],
                     ["Peptic ulcer", "Gastric ulcer", "Duodenal ulcer disease", "Gastrointestinal ulcer",
                      "Acute peptic ulcer", "Chronic peptic ulcer", "Acute gastric ulcer with perforation",
                      "Acute gastric ulcer with hemorrhage", "Acute peptic ulcer with hemorrhage"]),
    "Acidity / reflux": (["acidity", "gerd", "reflux", "acid reflux", "heartburn"],
                         ["Gastroesophageal reflux disease", "Peptic reflux disease", "Heartburn"]),
    "Pregnancy": (["pregnancy", "pregnant"],
                  ["Pregnancy, function", "Third trimester pregnancy", "Second trimester pregnancy"]),
    "Breastfeeding": (["breastfeeding", "breast feeding", "lactation", "nursing mother"],
                      ["Breastfeeding (mother)", "Lactation"]),
    "Heart failure": (["heart failure", "chf", "congestive heart failure", "weak heart"],
                      ["Heart failure", "Chronic heart failure", "Congestive heart failure", "Acute heart failure",
                       "Decompensated cardiac failure", "Left heart failure", "Decompensated chronic heart failure",
                       "Worsening of Chronic Heart Failure", "High output heart failure",
                       "Acute exacerbation of chronic congestive heart failure"]),
    "Heart attack (past or recent)": (["heart attack", "myocardial infarction", "mi"],
                                      ["Myocardial infarction", "Myocardial infarction in recovery phase",
                                       "Non-Q wave myocardial infarction"]),
    "Angina / coronary artery disease": (["angina", "coronary artery disease", "cad", "chest pain heart"],
                                         ["Angina pectoris", "Disorder of coronary artery", "Coronary arteriosclerosis",
                                          "Acute coronary syndrome", "Prinzmetal angina", "Progressive Angina Pectoris"]),
    "Stroke": (["stroke", "cva", "brain stroke", "paralysis"],
               ["Cerebrovascular accident", "Cerebrovascular disease", "Acute cerebrovascular insufficiency",
                "Acute Thromboembolic Stroke", "Hemorrhagic cerebral infarction", "Cerebral infarction",
                "Cerebral hemorrhage"]),
    "Slow or irregular heartbeat": (["arrhythmia", "irregular heartbeat", "slow heart rate", "bradycardia", "heart block",
                                     "long qt", "qt prolongation"],
                                    ["Prolonged QT interval", "Congenital long QT syndrome", "Bradycardia",
                                     "Sinus bradycardia", "Heart block", "First Degree Atrioventricular Heart Block",
                                     "Tachyarrhythmia", "Life-Threatening Cardiac Arrhythmias"]),
    "Atrial fibrillation": (["atrial fibrillation", "af", "afib"], ["Atrial fibrillation"]),
    "Bleeding disorder": (["bleeding disorder", "bleeding", "haemophilia", "hemophilia", "clotting disorder"],
                          ["Blood coagulation disorder", "Hemophilia", "Hemorrhage"]),
    "Anaemia": (["anaemia", "anemia", "low hb", "low haemoglobin", "low hemoglobin"],
                ["Anemia", "Hemolytic anemia", "Aplastic anemia", "Megaloblastic anemia",
                 "Megaloblastic anemia due to folate deficiency"]),
    "G6PD deficiency": (["g6pd", "g6pd deficiency"],
                        ["Anemia due to enzyme deficiency", "Glucose-6-phosphate dehydrogenase deficiency anemia"]),
    "High cholesterol": (["high cholesterol", "cholesterol", "hyperlipidemia", "hyperlipidaemia", "dyslipidemia",
                          "lipids"],
                         ["Hypercholesterolemia", "Hyperlipidemia", "Mixed hyperlipidemia", "Dyslipidemia"]),
    "Depression": (["depression", "depressed"], ["Depressive disorder", "Severe depression", "Major depressive disorder"]),
    "Epilepsy / seizures": (["epilepsy", "seizures", "seizure", "fits", "convulsions"],
                            ["Epilepsy", "Uncontrolled Epilepsy", "Lowered convulsive threshold", "Partial seizure",
                             "Tonic-clonic seizure", "Tonic-clonic epilepsy", "Idiopathic generalized epilepsy",
                             "Mixed Epilepsy", "Absence seizure", "Myoclonic seizure"]),
    "Glaucoma": (["glaucoma"],
                 ["Glaucoma", "Angle-closure glaucoma", "Open-angle glaucoma", "Secondary angle-closure glaucoma",
                  "Secondary glaucoma", "Primary Closed Angle Glaucoma", "Pupillary Block Glaucoma",
                  "Aggravated Glaucoma", "Malignant glaucoma", "Neovascular glaucoma"]),
    "Gout": (["gout", "uric acid", "high uric acid"], ["Gout", "Hyperuricemia"]),
    "Underactive thyroid": (["hypothyroidism", "low thyroid", "underactive thyroid", "thyroid"],
                            ["Hypothyroidism", "Mild Hypothyroidism", "Myxedema", "Hashimoto thyroiditis"]),
    "Overactive thyroid": (["hyperthyroidism", "overactive thyroid", "thyrotoxicosis"],
                           ["Hyperthyroidism", "Thyrotoxicosis", "Thyrotoxic crisis"]),
    "Enlarged prostate": (["prostate", "enlarged prostate", "bph", "urinary retention"], ["Benign prostatic hyperplasia"]),
    "Myasthenia gravis": (["myasthenia", "myasthenia gravis"], ["Myasthenia gravis"]),
    "Parkinson's disease": (["parkinson", "parkinsons", "parkinson's", "parkinson's disease"],
                            ["Parkinsonism", "Parkinson's disease"]),
    "Dementia": (["dementia", "alzheimer", "alzheimers", "alzheimer's"],
                 ["Senile dementia", "Dementia", "Alzheimer's disease"]),
    "Tuberculosis": (["tb", "tuberculosis"],
                     ["Acute tuberculosis", "Inactive tuberculosis", "Tuberculosis", "Pulmonary tuberculosis",
                      "Active tuberculosis"]),
    "Piles": (["piles", "hemorrhoids", "haemorrhoids"], ["Hemorrhoids", "Bleeding hemorrhoids"]),
    # the next four are conditions the Beers Criteria (Table 3) warn about in older adults
    "Fainting (syncope)": (["fainting", "faint", "syncope", "blackouts", "passing out"],
                           ["Syncope", "Micturition syncope", "Syncope due to Bradycardia", "Syncope due to Heart Block"]),
    "Delirium": (["delirium", "acute confusion", "sudden confusion"], ["Delirium"]),
    "History of falls or fractures": (["falls", "fall", "frequent falls", "fracture", "fractures", "broken bone",
                                       "history of falls", "osteoporosis fracture"],
                                      ["At risk of osteoporotic fracture", "Fracture of bone", "Fracture of femur",
                                       "Pathological fracture"]),
    "Urinary incontinence": (["urinary incontinence", "incontinence", "urine leakage", "leaking urine"],
                             ["Urinary incontinence", "Urge incontinence of urine", "Female stress incontinence"]),
}

# Each rule: the side effect (Hetionet names, regex), which drugs cause it (ATC class prefixes or names),
# and which conditions a second drug would be treating (DrugCentral names, regex).
CASCADE_RULES = [
    {"effect": "ankle swelling (oedema)", "effect_re": "(?i)oedema( peripheral| aggravated)?",
     "cause_atc": ["C08"], "cause_names": [], "treat_re": "(?i)(edema|peripheral edema|peripheral edema due to .*|edema due to .*|renal disease with edema)"},
    {"effect": "raised blood pressure", "effect_re": "(?i)hypertension",
     "cause_atc": ["M01A", "H02A"], "cause_names": [],
     "treat_re": "(?i)(hypertensive disorder|essential hypertension|malignant (essential )?hypertension)"},
    {"effect": "stomach irritation or ulcer", "effect_re": "(?i)(dyspepsia|gastric ulcer|duodenal ulcer|chronic peptic ulcer|peptic ulcer|gastritis|gastrooesophageal reflux disease)",
     "cause_atc": ["M01A", "B01AC", "H02A"], "cause_names": [],
     "treat_re": "(?i)(peptic ulcer|gastric ulcer|duodenal ulcer.*|gastroesophageal reflux disease|heartburn|erosive esophagitis)"},
    {"effect": "raised uric acid or gout", "effect_re": "(?i)(hyperuricaemia|gout|gout acute|gout attack|gouty arthritis)",
     "cause_atc": ["C03A", "C03C"], "cause_names": ["pyrazinamide", "ethambutol"],
     "treat_re": "(?i)(gout|articular gout|hyperuricemia)"},
    {"effect": "low potassium", "effect_re": "(?i)hypokalaemia",
     "cause_atc": ["C03A", "C03C", "H02A"], "cause_names": [], "treat_re": "(?i)hypokalemia.*"},
    {"effect": "constipation", "effect_re": "(?i)constipation( aggravated)?",
     "cause_atc": ["N02A", "C08DA", "N06AA", "A12AA"], "cause_names": [], "treat_re": "(?i)constipation"},
    {"effect": "dry cough", "effect_re": "(?i)cough( increased)?",
     "cause_atc": ["C09A"], "cause_names": [], "treat_re": "(?i)cough"},
    {"effect": "drug-induced parkinsonism or stiffness",
     "effect_re": "(?i)(drug-induced parkinsonism|parkinsonism|extrapyramidal disorder|extrapyramidal symptoms)",
     "cause_atc": ["N05A", "A03FA", "N07CA"], "cause_names": [],
     "treat_re": "(?i)(parkinsonism|parkinson's disease|extrapyramidal disease)"},
    {"effect": "raised blood sugar", "effect_re": "(?i)(hyperglycaemia|diabetes mellitus|blood glucose increased)",
     "cause_atc": ["H02A", "C03A", "N05AH", "N05AX"], "cause_names": [],
     "treat_re": "(?i)(diabetes mellitus.*|type 2 diabetes.*)"},
    {"effect": "underactive thyroid", "effect_re": "(?i)hypothyroidism",
     "cause_atc": ["C01BD"], "cause_names": ["lithium carbonate", "lithium"], "treat_re": "(?i)hypothyroidism"},
    {"effect": "tremor", "effect_re": "(?i)(tremor|tremor fine)",
     "cause_atc": ["N03AG", "R03AC", "R03CC"], "cause_names": ["lithium carbonate", "lithium"], "treat_re": "(?i)essential tremor"},
    {"effect": "diarrhoea", "effect_re": "(?i)(diarrhoea|antibiotic-associated diarrhea)",
     "cause_atc": ["J01", "A10BA"], "cause_names": [], "treat_re": "(?i)(diarrh(o)?ea.*|traveler's diarrhea)"},
    {"effect": "thrush or fungal infection", "effect_re": "(?i).*candid.*",
     "cause_atc": ["J01", "H02A", "R03BA"], "cause_names": [], "treat_re": "(?i).*candid.*"},
    {"effect": "dizziness or vertigo", "effect_re": "(?i)(dizziness|vertigo|dizziness postural)",
     "cause_atc": ["C02", "C03", "C07", "C08", "C09", "N03"], "cause_names": [],
     "treat_re": "(?i)(vertigo.*|m.ni.re's disease|dizziness)"},
    {"effect": "difficulty passing urine", "effect_re": "(?i)urinary retention",
     "cause_atc": ["N04A", "A03B", "N06AA", "R06A"], "cause_names": [],
     "treat_re": "(?i)(benign prostatic hyperplasia|urinary retention)"},
    {"effect": "sleeplessness", "effect_re": "(?i)(insomnia|initial insomnia)",
     "cause_atc": ["N06AB", "N06B", "R03CC", "H02A"], "cause_names": [], "treat_re": "(?i)insomnia.*"},
]

# What an interaction can actually do to the patient. DDInter only gives a severity (Major/Moderate/Minor), so a
# pair is explained by the effect groups BOTH drugs belong to: two drugs that each slow the heart are risky together
# for that reason. A drug is in a group by ATC class prefix, by name, or by a side effect recorded in the graph
# (Hetionet; only for QT, which drug labels report reliably: other side effects there are too noisy, e.g. ibuprofen
# is listed with "respiratory depression" from combination-product labels). Ordered most dangerous first. alcohol: ethanol belongs to the group. stack: warn when 3+ medicines
# in one list share it (off where 3 at once is normal treatment, e.g. three blood pressure medicines).
EFFECT_GROUPS = [
    {"id": "heart_rhythm", "title": "Heart rhythm",
     "what": "Both can slow the heartbeat or upset its rhythm. Together this can cause a dangerous irregular heartbeat.",
     "watch": "fainting, a racing or pounding heartbeat, sudden dizziness. Get urgent help if someone faints.",
     "atc": ["C01B", "C01AA", "C07", "C08D", "N05A", "N06AA", "J01FA", "J01MA", "P01BA", "P01BC", "L04AE"],
     "names": ["citalopram", "escitalopram", "domperidone", "ondansetron", "methadone", "fluconazole", "voriconazole",
               "ketoconazole", "sotalol", "ivabradine", "donepezil", "hydroxyzine", "trazodone"],
     "side_effects": ["Electrocardiogram QT prolonged", "Electrocardiogram QT corrected interval prolonged",
                      "Torsade de pointes"], "alcohol": False, "stack": True},
    {"id": "serotonin", "title": "Serotonin syndrome",
     "what": "Both raise serotonin, a brain chemical. Too much of it causes serotonin syndrome, which can be life-threatening.",
     "watch": "restlessness, confusion, high fever, heavy sweating, shaking, muscle twitching, a fast heartbeat.",
     "atc": ["N06AB", "N06AF", "N06AA", "N02CC", "N04BD"],
     "names": ["venlafaxine", "desvenlafaxine", "duloxetine", "milnacipran", "trazodone", "vilazodone", "vortioxetine",
               "mirtazapine", "tramadol", "tapentadol", "fentanyl", "methadone", "pethidine", "dextromethorphan",
               "linezolid", "lithium carbonate", "lithium citrate", "buspirone", "cyclobenzaprine", "levomilnacipran",
               "nefazodone", "sibutramine"],
     "side_effects": [], "alcohol": False, "stack": True},
    {"id": "drowsiness", "title": "Drowsiness and slowed breathing",
     "what": "Both slow down the brain. Together they can cause heavy drowsiness, confusion, falls and, at worst, slowed breathing.",
     "watch": "being very sleepy or hard to wake, slurred speech, slow or shallow breathing. Do not drive.",
     "atc": ["N05A", "N05B", "N05C", "N02A", "N03", "N06A", "N07BC", "R06AA", "R06AB", "R06AD", "R06AE", "M03B"],
     "names": ["clonidine"], "side_effects": [], "alcohol": True, "stack": True},
    {"id": "bleeding", "title": "Bleeding",
     "what": "Both make bleeding more likely. Together the risk adds up, especially bleeding in the stomach.",
     "watch": "unusual bruising, black or bloody stools, vomiting blood, blood in urine, nosebleeds or cuts that will not stop.",
     "atc": ["B01A", "M01A", "N02BA", "N06AB"],
     "names": ["venlafaxine", "desvenlafaxine", "duloxetine", "ibrutinib"], "side_effects": [], "alcohol": True, "stack": True},
    {"id": "low_sugar", "title": "Low blood sugar",
     "what": "Both can lower blood sugar. Together it can drop too low.",
     "watch": "shaking, sweating, sudden hunger, confusion, fainting. Take something sugary and get help.",
     "atc": ["A10A", "A10BB", "A10BX", "J01MA"], "names": ["quinine"], "side_effects": [], "alcohol": True, "stack": True},
    {"id": "immune", "title": "Weaker immune system",
     "what": "Both can lower white blood cells or weaken the immune system. Together infections become more likely and more serious.",
     "watch": "fever, sore throat, mouth ulcers, infections that keep coming back. A blood count test may be needed.",
     "atc": ["L01", "L04", "H02AB"],
     "names": ["clozapine", "carbamazepine", "methotrexate", "azathioprine", "mycophenolate mofetil", "deferiprone",
               "propylthiouracil", "carbimazole", "thiamazole", "sulfasalazine", "ganciclovir", "valganciclovir",
               "zidovudine", "chloramphenicol"], "side_effects": [], "alcohol": False, "stack": True},
    {"id": "potassium", "title": "High potassium",
     "what": "Both raise potassium in the blood. Too much potassium can upset the heart's rhythm.",
     "watch": "muscle weakness, tiredness, tingling, an irregular heartbeat. A blood test is needed to check.",
     "atc": ["C09", "C03DA", "A12B", "B01AB"],
     "names": ["amiloride", "triamterene", "trimethoprim", "ciclosporin", "tacrolimus", "drospirenone"],
     "side_effects": [], "alcohol": False, "stack": True},
    {"id": "seizures", "title": "Seizures (fits)",
     "what": "Both can make seizures more likely. Together the risk goes up, more so in people with epilepsy.",
     "watch": "a seizure (fit), sudden jerking movements, blackouts.",
     "atc": ["N05A", "N06AA", "J01MA", "J01DH"],
     "names": ["tramadol", "tapentadol", "bupropion", "theophylline", "isoniazid", "pethidine", "mefloquine"],
     "side_effects": [], "alcohol": False, "stack": True},
    {"id": "low_bp", "title": "Low blood pressure",
     "what": "Both lower blood pressure. Together it can drop too far.",
     "watch": "dizziness or light-headedness, especially when standing up, fainting, falls.",
     "atc": ["C02", "C03", "C07", "C08", "C09", "C01DA", "G04CA", "G04BE", "N05A", "N04B"],
     "names": ["trazodone"], "side_effects": [], "alcohol": True, "stack": False},
    {"id": "kidney", "title": "Kidney strain",
     "what": "Both can strain the kidneys. Together they can reduce how well the kidneys work.",
     "watch": "passing much less urine, swollen legs or ankles, unusual tiredness. Kidney blood tests may be needed.",
     "atc": ["M01A", "C09", "C03", "J01G", "L01XA"],
     "names": ["vancomycin", "lithium carbonate", "lithium citrate", "methotrexate", "amphotericin b",
               "tenofovir disoproxil", "ciclosporin", "tacrolimus", "colistin", "polymyxin b"],
     "side_effects": [], "alcohol": False, "stack": True},
    {"id": "liver", "title": "Liver strain",
     "what": "Both put strain on the liver. Together liver damage is more likely.",
     "watch": "yellow eyes or skin, dark urine, pain in the upper right belly, loss of appetite.",
     "atc": ["J04AB", "J04AC", "J04AK"],
     "names": ["paracetamol", "methotrexate", "valproic acid", "ketoconazole", "amiodarone", "leflunomide", "nevirapine",
               "isoniazid", "rifampicin", "pyrazinamide", "terbinafine", "diclofenac", "nimesulide"],
     "side_effects": [], "alcohol": True, "stack": True},
    {"id": "anticholinergic", "title": "Confusion, constipation, trouble passing urine",
     "what": "Both block acetylcholine, a nerve signal. Together, especially in older people, this can cause confusion, "
             "constipation and trouble passing urine.",
     "watch": "new confusion or memory problems, severe constipation, not able to pass urine, blurred vision.",
     "atc": ["N04A", "A03AA", "A03B", "G04BD", "R06AA", "R06AB", "R06AD", "N06AA"],
     # the names include every drug on the AGS Beers Criteria 2023 Table 7 (strongly anticholinergic)
     "names": ["clozapine", "olanzapine", "quetiapine", "chlorpromazine", "thioridazine", "promethazine", "hydroxyzine",
               "paroxetine", "disopyramide", "cyproheptadine", "amitriptyline", "amoxapine", "clomipramine",
               "desipramine", "doxepin", "imipramine", "nortriptyline", "prochlorperazine", "brompheniramine",
               "chlorphenamine", "dimenhydrinate", "diphenhydramine", "doxylamine", "meclozine", "triprolidine",
               "darifenacin", "fesoterodine", "flavoxate", "oxybutynin", "solifenacin", "tolterodine", "trospium",
               "benzatropine", "trihexyphenidyl", "perphenazine", "atropine", "clidinium", "dicycloverine",
               "homatropine", "hyoscyamine", "scopolamine", "cyclobenzaprine", "orphenadrine"],
     "side_effects": [], "alcohol": False, "stack": True},
]

# What each severity means to a patient, and what every other kind of finding means
SEVERITY_MEANING = {
    "Major": "Serious: this combination can cause harm that needs medical attention. It is usually avoided; if both "
             "are really needed, the doctor should check on the patient closely.",
    "Moderate": "Can make a side effect worse or change how well one of the medicines works. Often still used, "
                "with care, a dose change or extra check-ups.",
    "Minor": "Small effect. Usually nothing needs to change, but mention it to the doctor or pharmacist.",
    "Unknown": "Recorded as an interaction, but the source does not say how serious. Ask a pharmacist.",
}
ALCOHOL_MEANING = {
    "Major": "Avoid alcohol completely while taking this medicine.",
    "Moderate": "Best avoided. If drinking at all, keep it to a little and do not drive.",
    "Minor": "Small effect. Drink only in moderation.",
    "Unknown": "Recorded as an interaction, but the source does not say how serious. Ask a pharmacist.",
}

# How drug labels name groups of medicines ("Avoid use with NSAIDs"), and the ATC class prefixes that group means.
# A label sentence naming a group is shown for a pair when the other drug is in one of these classes.
# Group ids from EFFECT_GROUPS can stand in for a list of classes ("drugs that prolong the QT interval").
LABEL_CLASS_TERMS = {
    r"nsaids?|non-?steroidal anti-?inflammatory": ["M01A"],
    r"anticoagulants?|warfarin-type|vitamin k antagonists?": ["B01AA", "B01AE", "B01AF", "B01AB"],
    r"antiplatelets?|platelet (?:aggregation )?inhibitors?": ["B01AC"],
    r"ssris?|selective serotonin reuptake inhibitors?": ["N06AB"],
    r"snris?|serotonin[- ]norepinephrine reuptake inhibitors?": ["N06AX"],
    r"maois?|monoamine oxidase inhibitors?": ["N06AF", "N04BD"],
    r"tricyclic antidepressants?|tcas?": ["N06AA"],
    r"serotonergic (?:drugs|agents|medications)": ["serotonin"],
    r"(?:drugs|medications|agents) (?:that|known to) prolong the qt|qt[- ]prolonging": ["heart_rhythm"],
    r"cns depressants?|central nervous system depressants?": ["drowsiness"],
    r"opioids?|opiates?|narcotic analgesics?": ["N02A", "N07BC"],
    r"benzodiazepines?": ["N05BA", "N05CD"],
    r"antipsychotics?|neuroleptics?": ["N05A"],
    r"diuretics?": ["C03"],
    r"potassium[- ]sparing diuretics?": ["C03DA", "C03DB"],
    r"potassium supplements?|potassium-containing": ["A12B"],
    r"ace inhibitors?|angiotensin[- ]converting enzyme inhibitors?": ["C09A", "C09B"],
    r"angiotensin (?:ii )?receptor (?:blockers?|antagonists?)|arbs?": ["C09C", "C09D"],
    r"beta[- ](?:adrenergic )?block(?:ers?|ing agents?)": ["C07"],
    r"calcium channel blockers?": ["C08"],
    r"antihypertensives?|antihypertensive (?:drugs|agents)": ["C02", "C03", "C07", "C08", "C09"],
    r"insulin|sulfonylureas?|insulin secretagogues?|antidiabetic (?:drugs|agents)": ["A10"],
    r"corticosteroids?|glucocorticoids?": ["H02"],
    r"fluoroquinolones?|quinolones?": ["J01MA"],
    r"macrolides?": ["J01FA"],
    r"azole antifungals?": ["J02AC"],
    r"statins?|hmg-coa reductase inhibitors?": ["C10AA"],
    r"antacids?": ["A02A"],
    r"proton pump inhibitors?|ppis?": ["A02BC"],
    r"anticholinergics?|antimuscarinics?": ["anticholinergic"],
    r"immunosuppressants?|immunosuppressive (?:drugs|agents|therapy)": ["immune"],
}

# Side effects worth showing from TWOSIDES (drug-pair reports to the US FDA). The raw data ranks rare, unrelated
# events highest (fractures, osteoarthritis: often the reason the patient was treated, not an effect), so only
# serious, recognisable events are kept, and they are ranked by how many reports name them.
REPORTED_EFFECTS = (
    r"(?i)(haemorrhage|bleeding|haematemesis|melaena|haematochezia|international normali[sz]ed ratio increased|"
    r"qt prolonged|torsade|arrhythmia|atrial fibrillation|ventricular (tachycardia|fibrillation)|bradycardia|"
    r"cardiac arrest|syncope|hypoglycaemia|hyperkalaemia|hyponatraemia|hypotension|renal failure|kidney injury|"
    r"renal impairment|hepatic failure|hepatotoxicity|liver injury|hepatitis|jaundice|serotonin syndrome|"
    r"neuroleptic malignant|seizure|convulsion|somnolence|sedation|respiratory (depression|arrest)|\bfall\b|"
    r"confusional state|delirium|coma|loss of consciousness|neutropenia|agranulocytosis|pancytopenia|"
    r"thrombocytopenia|lactic acidosis|rhabdomyolysis|stevens-johnson|toxic epidermal necrolysis|anaphyla|angioedema)"
)
